### ISSUE TITLE
Work with React

### ISSUE THREAD

**Issue by farskid** [github/accessibilityjs#19]
Is there a way to make it work in React applications?
I'm getting no output using it on React codebase.

**Comment by easingthemes** [comment]
It works fine.
Check fiddle: https://jsfiddle.net/lima_fil/gfgk7jdo/

What issues do you have?

**Comment by mislav** [comment]
Hvala, @easingthemes! 

Closing in favor of the working example linked. If some of this React approach can be encapsulated within our README documentation, please send us a PR.
